import type { InspectSpatialLayoutData } from "./types";

const HOME_OFFICE_INSPECT_DATA = {
  contractVersion: "1.0.0",
  baseRevision: 1,
  baseHash: "54314a64f990ba98d9244a679e81d4037fc97c6275936c12e38ec243ca6aeb2e",
  workingState: {
    schemaVersion: 1,
    templateId: "home-office",
    room: { widthMm: 3600, depthMm: 3000 },
    features: [
      { id: "door-main", catalogId: "door-900", wall: "west", offsetMm: 1950 },
      {
        id: "radiator-east",
        catalogId: "radiator-900",
        wall: "east",
        offsetMm: 850,
      },
      {
        id: "window-north",
        catalogId: "window-1400",
        wall: "north",
        offsetMm: 1100,
      },
    ],
    furniture: [
      {
        id: "chair-main",
        catalogId: "chair-600x600",
        xMm: 2500,
        yMm: 1300,
        rotationDeg: 0,
        locked: false,
      },
      {
        id: "desk-main",
        catalogId: "desk-1400x700",
        xMm: 2500,
        yMm: 500,
        rotationDeg: 0,
        locked: false,
      },
      {
        id: "storage-main",
        catalogId: "storage-800x400",
        xMm: 700,
        yMm: 600,
        rotationDeg: 0,
        locked: true,
      },
    ],
    constraints: [
      {
        constraintId: "c-door",
        type: "door_path_clear",
        strength: "required",
        featureId: "door-main",
        widthMm: 900,
      },
      {
        constraintId: "c-radiator",
        type: "feature_distance",
        strength: "required",
        itemId: "desk-main",
        featureId: "radiator-east",
        relation: "away",
        thresholdMm: 800,
      },
      {
        constraintId: "c-window",
        type: "feature_distance",
        strength: "preferred",
        itemId: "desk-main",
        featureId: "window-north",
        relation: "near",
        thresholdMm: 700,
      },
      {
        constraintId: "c-chair",
        type: "item_distance",
        strength: "preferred",
        itemAId: "chair-main",
        itemBId: "desk-main",
        relation: "near",
        thresholdMm: 500,
      },
    ],
  },
  catalog: {
    furniture: [
      {
        id: "desk-1400x700",
        kind: "desk",
        label: "Desk",
        widthMm: 1400,
        depthMm: 700,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "chair-600x600",
        kind: "chair",
        label: "Chair",
        widthMm: 600,
        depthMm: 600,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "storage-800x400",
        kind: "storage",
        label: "Storage",
        widthMm: 800,
        depthMm: 400,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "bed-2000x1600",
        kind: "bed",
        label: "Bed",
        widthMm: 2000,
        depthMm: 1600,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "nightstand-500x400",
        kind: "nightstand",
        label: "Nightstand",
        widthMm: 500,
        depthMm: 400,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "wardrobe-1200x600",
        kind: "wardrobe",
        label: "Wardrobe",
        widthMm: 1200,
        depthMm: 600,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "table-1200x800",
        kind: "table",
        label: "Table",
        widthMm: 1200,
        depthMm: 800,
        allowedRotations: [0, 90, 180, 270],
      },
      {
        id: "bookcase-800x350",
        kind: "bookcase",
        label: "Bookcase",
        widthMm: 800,
        depthMm: 350,
        allowedRotations: [0, 90, 180, 270],
      },
    ],
    features: [
      {
        id: "door-900",
        type: "door",
        label: "Door",
        spanMm: 900,
        depthMm: 0,
        keepOutDepthMm: 0,
      },
      {
        id: "window-1400",
        type: "window",
        label: "Window",
        spanMm: 1400,
        depthMm: 0,
        keepOutDepthMm: 0,
      },
      {
        id: "radiator-900",
        type: "radiator",
        label: "Radiator",
        spanMm: 900,
        depthMm: 150,
        keepOutDepthMm: 300,
      },
    ],
  },
  coordinateSystem: {
    origin: "north-west",
    xAxis: "east",
    yAxis: "south",
    unit: "mm",
    integersOnly: true,
  },
  limits: {
    roomMinMm: 2000,
    roomMaxMm: 12000,
    maxFeatures: 8,
    maxFurniture: 8,
    maxConstraints: 8,
    maxOptions: 3,
    maxMovesPerOption: 8,
    doorPathWidthMinMm: 500,
    doorPathWidthMaxMm: 1600,
    distanceThresholdMinMm: 0,
    distanceThresholdMaxMm: 4000,
    dragSnapMm: 50,
    rotationsDeg: [0, 90, 180, 270],
  },
  preview: { status: "none" },
} as const satisfies InspectSpatialLayoutData;

export function createHomeOfficeInspectData(): InspectSpatialLayoutData {
  return structuredClone(HOME_OFFICE_INSPECT_DATA);
}
