import type { Furniture } from "../domain/types";
import type { DomainStore, StoreSnapshot } from "../domain/store";
import { placementValid } from "../domain/geometry";

export function startDrag(event: PointerEvent, itemId: string, node: SVGGElement, snapshot: StoreSnapshot, store: DomainStore, render: () => void, status: (s:string)=>void): (() => void) | undefined {
  if (event.button !== 0 || !event.isPrimary || snapshot.preview) return;
  const item=snapshot.workingState.furniture.find(x=>x.id===itemId); if(!item||item.locked)return;
  const svg=node.ownerSVGElement; if(!svg)return; let active=true; const original=item; let candidate=item;
  try { node.setPointerCapture(event.pointerId); } catch { return; }
  const poseNodes=[node.querySelector("rect")!,node.querySelector("text")!];
  const originalTransforms=poseNodes.map(element=>element.getAttribute("transform"));
  const restorePose=()=>{node.dataset.xMm=String(original.xMm);node.dataset.yMm=String(original.yMm);poseNodes.forEach((element,index)=>{const transform=originalTransforms[index];if(transform==null)element.removeAttribute("transform");else element.setAttribute("transform",transform);});};
  let captureMonitor: number | undefined; let captureEstablished = false;
  const point=(e:PointerEvent): {x:number;y:number}|null=>{ try { const matrix=svg.getScreenCTM(); if(!matrix)return null; const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()); return Number.isFinite(p.x)&&Number.isFinite(p.y)?{x:p.x,y:p.y}:null; } catch{return null;} };
  const update=(e:PointerEvent)=>{if(!active||e.pointerId!==event.pointerId)return;const p=point(e);if(!p)return;candidate={...item,xMm:Math.round(p.x/50)*50,yMm:Math.round(p.y/50)*50};node.dataset.xMm=String(candidate.xMm);node.dataset.yMm=String(candidate.yMm);const rect=node.querySelector("rect")!; const dx=candidate.xMm-item.xMm,dy=candidate.yMm-item.yMm;rect.setAttribute("transform",`translate(${dx} ${dy})`);const text=node.querySelector("text")!;text.setAttribute("transform",`translate(${dx} ${dy})`);};
  const clean=(commit:boolean,silent=false)=>{if(!active)return;active=false;if(captureMonitor!==undefined)cancelAnimationFrame(captureMonitor);node.removeEventListener("pointermove",update);node.removeEventListener("pointerup",up);node.removeEventListener("pointercancel",cancel);node.removeEventListener("lostpointercapture",lost);node.removeEventListener("gotpointercapture",got);svg.removeEventListener("lostpointercapture",lost,true);try{if(node.hasPointerCapture(event.pointerId))node.releasePointerCapture(event.pointerId);}catch{} if(!commit)restorePose(); if(silent)return; if(!commit){render();return;} if(candidate.xMm===original.xMm&&candidate.yMm===original.yMm){render();return;} if(!placementValid(candidate as Furniture,snapshot.workingState.room,snapshot.workingState.furniture,snapshot.workingState.features)){status("Move rejected: outside bounds, overlap, or radiator keep-out.");render();return;} const result=store.updateFurniturePose(itemId,candidate);status(result.ok?`${itemId} moved to ${candidate.xMm}, ${candidate.yMm} mm.`:result.error.message);render();};
  const up=(e:PointerEvent)=>{if(e.pointerId===event.pointerId)clean(true)};const cancel=(e:PointerEvent)=>{if(e.pointerId===event.pointerId)clean(false)};const lost=(e:PointerEvent)=>{if(e.pointerId===event.pointerId)clean(false)};const monitorCapture=()=>{if(!active)return;if(captureEstablished&&!node.hasPointerCapture(event.pointerId)){clean(false);return}captureMonitor=requestAnimationFrame(monitorCapture)};const got=()=>{captureEstablished=true}; node.addEventListener("pointermove",update);node.addEventListener("pointerup",up);node.addEventListener("pointercancel",cancel);node.addEventListener("lostpointercapture",lost);node.addEventListener("gotpointercapture",got);svg.addEventListener("lostpointercapture",lost,true);captureMonitor=requestAnimationFrame(monitorCapture);
  return () => clean(false, true);
}
